/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouthRouteImport } from './routes/youth'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as TrendDeskRouteImport } from './routes/trend-desk'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SocialRouteImport } from './routes/social'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as MapRouteImport } from './routes/map'
import { Route as LinkToStoryRouteImport } from './routes/link-to-story'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FoodRouteImport } from './routes/food'
import { Route as FactCheckRouteImport } from './routes/fact-check'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as BreakingRouteImport } from './routes/breaking'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SectionNameRouteImport } from './routes/section.$name'
import { Route as NeighborhoodsSlugRouteImport } from './routes/neighborhoods.$slug'
import { Route as GuideOttawaRouteImport } from './routes/guide.ottawa'
import { Route as GuideCanadaRouteImport } from './routes/guide.canada'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as ApiPublicTrafficRadioRouteImport } from './routes/api/public/traffic-radio'
import { Route as ApiPublicOttawaTrafficRouteImport } from './routes/api/public/ottawa-traffic'

const YouthRoute = YouthRouteImport.update({
  id: '/youth',
  path: '/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendDeskRoute = TrendDeskRouteImport.update({
  id: '/trend-desk',
  path: '/trend-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkToStoryRoute = LinkToStoryRouteImport.update({
  id: '/link-to-story',
  path: '/link-to-story',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckRoute = FactCheckRouteImport.update({
  id: '/fact-check',
  path: '/fact-check',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakingRoute = BreakingRouteImport.update({
  id: '/breaking',
  path: '/breaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionNameRoute = SectionNameRouteImport.update({
  id: '/section/$name',
  path: '/section/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsSlugRoute = NeighborhoodsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NeighborhoodsRoute,
} as any)
const GuideOttawaRoute = GuideOttawaRouteImport.update({
  id: '/guide/ottawa',
  path: '/guide/ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideCanadaRoute = GuideCanadaRouteImport.update({
  id: '/guide/canada',
  path: '/guide/canada',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrafficRadioRoute = ApiPublicTrafficRadioRouteImport.update({
  id: '/api/public/traffic-radio',
  path: '/api/public/traffic-radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOttawaTrafficRoute = ApiPublicOttawaTrafficRouteImport.update({
  id: '/api/public/ottawa-traffic',
  path: '/api/public/ottawa-traffic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/breaking': typeof BreakingRoute
  '/deals': typeof DealsRoute
  '/donate': typeof DonateRoute
  '/ethics': typeof EthicsRoute
  '/events': typeof EventsRoute
  '/fact-check': typeof FactCheckRoute
  '/food': typeof FoodRoute
  '/jobs': typeof JobsRoute
  '/kids': typeof KidsRoute
  '/link-to-story': typeof LinkToStoryRoute
  '/map': typeof MapRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/pulse': typeof PulseRoute
  '/radio': typeof RadioRoute
  '/social': typeof SocialRoute
  '/solutions': typeof SolutionsRoute
  '/sports': typeof SportsRoute
  '/submit': typeof SubmitRoute
  '/traffic': typeof TrafficRoute
  '/trend-desk': typeof TrendDeskRoute
  '/weather': typeof WeatherRoute
  '/youth': typeof YouthRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/guide/canada': typeof GuideCanadaRoute
  '/guide/ottawa': typeof GuideOttawaRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/section/$name': typeof SectionNameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/ottawa-traffic': typeof ApiPublicOttawaTrafficRoute
  '/api/public/traffic-radio': typeof ApiPublicTrafficRadioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/breaking': typeof BreakingRoute
  '/deals': typeof DealsRoute
  '/donate': typeof DonateRoute
  '/ethics': typeof EthicsRoute
  '/events': typeof EventsRoute
  '/fact-check': typeof FactCheckRoute
  '/food': typeof FoodRoute
  '/jobs': typeof JobsRoute
  '/kids': typeof KidsRoute
  '/link-to-story': typeof LinkToStoryRoute
  '/map': typeof MapRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/pulse': typeof PulseRoute
  '/radio': typeof RadioRoute
  '/social': typeof SocialRoute
  '/solutions': typeof SolutionsRoute
  '/sports': typeof SportsRoute
  '/submit': typeof SubmitRoute
  '/traffic': typeof TrafficRoute
  '/trend-desk': typeof TrendDeskRoute
  '/weather': typeof WeatherRoute
  '/youth': typeof YouthRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/guide/canada': typeof GuideCanadaRoute
  '/guide/ottawa': typeof GuideOttawaRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/section/$name': typeof SectionNameRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/ottawa-traffic': typeof ApiPublicOttawaTrafficRoute
  '/api/public/traffic-radio': typeof ApiPublicTrafficRadioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/breaking': typeof BreakingRoute
  '/deals': typeof DealsRoute
  '/donate': typeof DonateRoute
  '/ethics': typeof EthicsRoute
  '/events': typeof EventsRoute
  '/fact-check': typeof FactCheckRoute
  '/food': typeof FoodRoute
  '/jobs': typeof JobsRoute
  '/kids': typeof KidsRoute
  '/link-to-story': typeof LinkToStoryRoute
  '/map': typeof MapRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/pulse': typeof PulseRoute
  '/radio': typeof RadioRoute
  '/social': typeof SocialRoute
  '/solutions': typeof SolutionsRoute
  '/sports': typeof SportsRoute
  '/submit': typeof SubmitRoute
  '/traffic': typeof TrafficRoute
  '/trend-desk': typeof TrendDeskRoute
  '/weather': typeof WeatherRoute
  '/youth': typeof YouthRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/guide/canada': typeof GuideCanadaRoute
  '/guide/ottawa': typeof GuideOttawaRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/section/$name': typeof SectionNameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/ottawa-traffic': typeof ApiPublicOttawaTrafficRoute
  '/api/public/traffic-radio': typeof ApiPublicTrafficRadioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/breaking'
    | '/deals'
    | '/donate'
    | '/ethics'
    | '/events'
    | '/fact-check'
    | '/food'
    | '/jobs'
    | '/kids'
    | '/link-to-story'
    | '/map'
    | '/neighborhoods'
    | '/pulse'
    | '/radio'
    | '/social'
    | '/solutions'
    | '/sports'
    | '/submit'
    | '/traffic'
    | '/trend-desk'
    | '/weather'
    | '/youth'
    | '/admin/sources'
    | '/article/$slug'
    | '/guide/canada'
    | '/guide/ottawa'
    | '/neighborhoods/$slug'
    | '/section/$name'
    | '/admin/'
    | '/api/public/ottawa-traffic'
    | '/api/public/traffic-radio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/breaking'
    | '/deals'
    | '/donate'
    | '/ethics'
    | '/events'
    | '/fact-check'
    | '/food'
    | '/jobs'
    | '/kids'
    | '/link-to-story'
    | '/map'
    | '/neighborhoods'
    | '/pulse'
    | '/radio'
    | '/social'
    | '/solutions'
    | '/sports'
    | '/submit'
    | '/traffic'
    | '/trend-desk'
    | '/weather'
    | '/youth'
    | '/admin/sources'
    | '/article/$slug'
    | '/guide/canada'
    | '/guide/ottawa'
    | '/neighborhoods/$slug'
    | '/section/$name'
    | '/admin'
    | '/api/public/ottawa-traffic'
    | '/api/public/traffic-radio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/breaking'
    | '/deals'
    | '/donate'
    | '/ethics'
    | '/events'
    | '/fact-check'
    | '/food'
    | '/jobs'
    | '/kids'
    | '/link-to-story'
    | '/map'
    | '/neighborhoods'
    | '/pulse'
    | '/radio'
    | '/social'
    | '/solutions'
    | '/sports'
    | '/submit'
    | '/traffic'
    | '/trend-desk'
    | '/weather'
    | '/youth'
    | '/admin/sources'
    | '/article/$slug'
    | '/guide/canada'
    | '/guide/ottawa'
    | '/neighborhoods/$slug'
    | '/section/$name'
    | '/admin/'
    | '/api/public/ottawa-traffic'
    | '/api/public/traffic-radio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  BreakingRoute: typeof BreakingRoute
  DealsRoute: typeof DealsRoute
  DonateRoute: typeof DonateRoute
  EthicsRoute: typeof EthicsRoute
  EventsRoute: typeof EventsRoute
  FactCheckRoute: typeof FactCheckRoute
  FoodRoute: typeof FoodRoute
  JobsRoute: typeof JobsRoute
  KidsRoute: typeof KidsRoute
  LinkToStoryRoute: typeof LinkToStoryRoute
  MapRoute: typeof MapRoute
  NeighborhoodsRoute: typeof NeighborhoodsRouteWithChildren
  PulseRoute: typeof PulseRoute
  RadioRoute: typeof RadioRoute
  SocialRoute: typeof SocialRoute
  SolutionsRoute: typeof SolutionsRoute
  SportsRoute: typeof SportsRoute
  SubmitRoute: typeof SubmitRoute
  TrafficRoute: typeof TrafficRoute
  TrendDeskRoute: typeof TrendDeskRoute
  WeatherRoute: typeof WeatherRoute
  YouthRoute: typeof YouthRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  GuideCanadaRoute: typeof GuideCanadaRoute
  GuideOttawaRoute: typeof GuideOttawaRoute
  SectionNameRoute: typeof SectionNameRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicOttawaTrafficRoute: typeof ApiPublicOttawaTrafficRoute
  ApiPublicTrafficRadioRoute: typeof ApiPublicTrafficRadioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youth': {
      id: '/youth'
      path: '/youth'
      fullPath: '/youth'
      preLoaderRoute: typeof YouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-desk': {
      id: '/trend-desk'
      path: '/trend-desk'
      fullPath: '/trend-desk'
      preLoaderRoute: typeof TrendDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-to-story': {
      id: '/link-to-story'
      path: '/link-to-story'
      fullPath: '/link-to-story'
      preLoaderRoute: typeof LinkToStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-check': {
      id: '/fact-check'
      path: '/fact-check'
      fullPath: '/fact-check'
      preLoaderRoute: typeof FactCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaking': {
      id: '/breaking'
      path: '/breaking'
      fullPath: '/breaking'
      preLoaderRoute: typeof BreakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$name': {
      id: '/section/$name'
      path: '/section/$name'
      fullPath: '/section/$name'
      preLoaderRoute: typeof SectionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/$slug': {
      id: '/neighborhoods/$slug'
      path: '/$slug'
      fullPath: '/neighborhoods/$slug'
      preLoaderRoute: typeof NeighborhoodsSlugRouteImport
      parentRoute: typeof NeighborhoodsRoute
    }
    '/guide/ottawa': {
      id: '/guide/ottawa'
      path: '/guide/ottawa'
      fullPath: '/guide/ottawa'
      preLoaderRoute: typeof GuideOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/canada': {
      id: '/guide/canada'
      path: '/guide/canada'
      fullPath: '/guide/canada'
      preLoaderRoute: typeof GuideCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/traffic-radio': {
      id: '/api/public/traffic-radio'
      path: '/api/public/traffic-radio'
      fullPath: '/api/public/traffic-radio'
      preLoaderRoute: typeof ApiPublicTrafficRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ottawa-traffic': {
      id: '/api/public/ottawa-traffic'
      path: '/api/public/ottawa-traffic'
      fullPath: '/api/public/ottawa-traffic'
      preLoaderRoute: typeof ApiPublicOttawaTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NeighborhoodsRouteChildren {
  NeighborhoodsSlugRoute: typeof NeighborhoodsSlugRoute
}

const NeighborhoodsRouteChildren: NeighborhoodsRouteChildren = {
  NeighborhoodsSlugRoute: NeighborhoodsSlugRoute,
}

const NeighborhoodsRouteWithChildren = NeighborhoodsRoute._addFileChildren(
  NeighborhoodsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  BreakingRoute: BreakingRoute,
  DealsRoute: DealsRoute,
  DonateRoute: DonateRoute,
  EthicsRoute: EthicsRoute,
  EventsRoute: EventsRoute,
  FactCheckRoute: FactCheckRoute,
  FoodRoute: FoodRoute,
  JobsRoute: JobsRoute,
  KidsRoute: KidsRoute,
  LinkToStoryRoute: LinkToStoryRoute,
  MapRoute: MapRoute,
  NeighborhoodsRoute: NeighborhoodsRouteWithChildren,
  PulseRoute: PulseRoute,
  RadioRoute: RadioRoute,
  SocialRoute: SocialRoute,
  SolutionsRoute: SolutionsRoute,
  SportsRoute: SportsRoute,
  SubmitRoute: SubmitRoute,
  TrafficRoute: TrafficRoute,
  TrendDeskRoute: TrendDeskRoute,
  WeatherRoute: WeatherRoute,
  YouthRoute: YouthRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  GuideCanadaRoute: GuideCanadaRoute,
  GuideOttawaRoute: GuideOttawaRoute,
  SectionNameRoute: SectionNameRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicOttawaTrafficRoute: ApiPublicOttawaTrafficRoute,
  ApiPublicTrafficRadioRoute: ApiPublicTrafficRadioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
